RedeSocial/Controllers/SocialController.cs
using RedeSocial.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedeSocial.Controllers
{
    public class SocialController : Controller
    {
        private RedeSocialContext db = new RedeSocialContext();
        // GET: Social
        public ActionResult Index()
        {
            using (db = new RedeSocialContext())
            {
                if (Session.Count != 0)
                {
                    int id = (int)Session["IdUsuario"];
                    IQueryable<Publicacao> query = from i in db.Publicacao where i.IdUsuario == id orderby i.DtPublicacao descending select i;
                    ViewBag.List = query.ToList();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(myModels pub)
        {
            using (db = new RedeSocialContext())
            { 
                if (ModelState.Values.Count == 1)
                {
                    try
                    {
                        pub.publicacao.IdUsuario = (int)Session["IdUsuario"];
                        db.Database.ExecuteSqlCommand("Exec Publicar @Publicacao, @IdUsuario", 
                            new SqlParameter("@Publicacao",pub.publicacao.Publicacao1),
                            new SqlParameter("@IdUsuario",pub.publicacao.IdUsuario));
                        return RedirectToAction("Index");
                    } catch (Exception e)
                    {
                        ModelState.AddModelError("erro", "Deu errado");
                        return RedirectToAction("Index");
                    }
                }
            return View();
            }
        }

        public ActionResult Sair()
        {
            Session["IdUsuario"] = null;
            Session["Nome"] = null;
            Session["Email"] = null;
            return Redirect("~/Usuarios/Logar");
        }
    }
}

RedeSocial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RedeSocial</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A melhor Rede Social</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

RedeSocial/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RedeSocial</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Social", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Sair", "Sair", "Social", routeValues: null, htmlAttributes: new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A melhor Rede Social</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>